name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Vérification de structure HTML
      - name: Vérification HTML
        run: |
          if ! grep -iq "<html" index.html; then
            echo "Erreur : fichier HTML invalide."
            exit 1
          fi

      # Connexion à Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tresor_ethere:latest .

      # Push de l'image vers DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tresor_ethere:latest

  deploy_ftp:
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          dry-run: false
